apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  creationTimestamp: null
  name: "5067798921801294339"
  namespace: default
spec:
  interval: 30s
  ref:
    branch: main
  url: https://github.com/igordcard/anthosync
status: {}
